---
#---variables vg, lv, tamaÃ±o, punto de montura y formato fs
ctrlm: "VGAPPS,LVJAVA_CTM,5,/java_ctrlm,xfs"
oracle: "VGAPPS,LVJAVA_ORA,5,/java_oracle,xfs"
db2: "VGAPPS,LVJAVA_DB2,5,/java_db2,xfs"
mdw: "VGAPPS,LVJAVA_MDW,5,/java_mdw,xfs"

#---variables de api_dev
tower_base_url: "http://172.18.0.5:8052"
tower_token: "T3qIBMvwZMS9321AL39Dlm66HeB3iX"

#---variables comandos os
devnull: "2>/dev/null"
accionjtp:
  inventarioid: 2
  trabajoid: 76
  credemciales: "[6]"
  idcrqinc: "{{idcrqinc}}"
  tarea: "Proceso_LVM"
  demora: 2
  reintentos: 9999

java_software:
  java1.8.0: "java-1.8.0-openjdk-portable-1.8.0.452.b09-1.portable.jdk.el.x86_64.tar.xz"
  java11: "java-11-openjdk-11.0.23.0.9-2.portable.jdk.el.x86_64.tar.xz"
  java17: "java-17-openjdk-17.0.15.0.6-1.portable.jdk.el.x86_64.tar.xz"
  java21: "java-21-openjdk-21.0.7.0.6-1.portable.jdk.x86_64.tar.xz"