---
ctrlm: "VGAPPS,LVJAVA_CTM,5,/java_ctrlm"
oracle: "VGAPPS,LVJAVA_ORA,5,/java_oracle"
db2: "VGAPPS,LVJAVA_DB2,5,/java_db2"
mdw: "VGAPPS,LVJAVA_MDW,5,/java_mdw"

#---variables de api_dev
tower_base_url: "http://172.18.0.3:8052"
tower_token: "T3qIBMvwZMS9321AL39Dlm66HeB3iX"

#---variables comandos os
devnull: "2>/dev/null"
accionjtp:
  inventarioid: 2
  trabajoid: 76
  credemciales: "[6]"
  idcrqinc: "{{idcrqinc}}"
  tarea: "Proceso_LVM"
  demora: 2
  reintentos: 9999
  # vgn: "{{vgnm}}"
  # lvn: "{{lvnm}}"
  # lvsz: "{{mpsz}}"
  # mpn: "{{mpnm}}"
  # fst: "{{fstp}}"
