---
# - block:
#     - set_fact:
#         javavglvfs: |
#           {% if (javaop0 == 'Batch') and (javaop1 == 'Control-M') %}
#           VGAPPS,LVJAVA_CTM,/java_ctrlm,5
#           {% elif (javaop0 == 'Base_de_datos') and (javaop1 == 'Oracle') %}
#           VGAPPS,LVJAVA_ORA,/java_oracle,5
#           {% elif (javaop0 == 'Base_de_datos') and (javaop1 == 'Db2') %}
#           VGAPPS,LVJAVA_DB2,/java_db2,5
#           {% elif (javaop0 == 'Midlware') and (javaop1 == 'Jboss') %}
#           VGAPPS,LVJAVA_MDW,/java_mdw,5
#           {% else %}
#           "No selecciono ninguna opcion Java"
#           {% endif %}

# - block:
#     - debug:
#         msg: "{{javavglvfs|trim|replace('\n','')}}"

#     - set_fact:
#         vgnm: "{{javavglvfs.split(',')[0]}}"
#         lvnm: "{{javavglvfs.split(',')[1]}}"
#         mpnm: "{{javavglvfs.split(',')[2]}}"
#         mpsz: "{{javavglvfs.split(',')[3]}}"

- block:
    - name: Validar que exista el VG - {{javavglvfs.split(',')[0]|trim}}
      become: true
      shell: vgs {{devnull}} --units g | tr -s ' ' , | cut -d, -f2 | grep {{vgnm}}
      register: rstlopvgnm
      failed_when: rstlopvgnm.rc not in [0, 1]

    - set_fact:
        vgconfnm: "{{rstlopvgnm.stdout|default('no_vg_found')|trim}}"

    - name: Validar el espacio libre del VG - {{javavglvfs.split(',')[0]|trim}}
      become: true
      shell: vgs {{devnull}} --units g | tr -s ' ' , | grep {{vgnm}} | cut -d, -f8 | cut -d. -f1
      register: rstlopvgsz
      failed_when: rstlopvgsz.rc not in [0, 1]

    - set_fact:
        vgconfsz: "{{rstlopvgsz.stdout|default('0')|trim}}"

    - set_fact:
        vgconftsz: "{{vgconfsz | int - 5}}"

    - set_fact:
        run_playbook: |
          {% if (vgconfnm == 'VGAPPS') and (vgconftsz | int >= 10) %}
          ['validar/chklv']
          {% else %}
          ['llamar/api_lvm']
          {% endif %}

    - name: Se encontrol {{javavglvfs.split(',')[0]|trim}} se ejecuta la tarea {{run_playbook}}
      include_tasks: "{{ tareas1 }}.yml"
      loop: "{{ run_playbook }}"
      loop_control:
        loop_var: tareas1